# Generated by Django 4.0.1 on 2022-02-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fundamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companies', models.TextField()),
                ('trailing_PE', models.FloatField(max_length=20)),
                ('return_on_equity', models.FloatField(max_length=20)),
                ('return_on_assets', models.FloatField(max_length=20)),
                ('book_value', models.FloatField(max_length=20)),
                ('trailing_EPS', models.FloatField(max_length=20)),
                ('price_to_book', models.FloatField(max_length=20)),
                ('sector', models.TextField()),
                ('payout_ratio', models.FloatField(max_length=20)),
                ('market_cap', models.BigIntegerField()),
                ('trailing_peg_ratio', models.FloatField(max_length=20)),
            ],
        ),
    ]
