# Generated by Django 4.0.1 on 2022-02-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_technical2'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.TextField()),
                ('Lastname', models.TextField()),
                ('Username', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('watchlist', models.JSONField(default='{}')),
                ('portfolio', models.JSONField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='tsla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField(max_length=20)),
                ('high', models.FloatField(max_length=20)),
                ('low', models.FloatField(max_length=20)),
                ('close', models.FloatField(max_length=20)),
                ('adj_close', models.FloatField(max_length=20)),
                ('volume', models.IntegerField()),
                ('rsi', models.FloatField(max_length=20)),
                ('macd', models.TextField()),
                ('bollingerband_signal', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='technical2',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
