# Generated by Django 4.0.1 on 2022-02-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_signup_detail_tsla_technical2_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='technical2',
            name='Holdings',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
