# Generated by Django 4.0.2 on 2022-02-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_technical2_holdings'),
    ]

    operations = [
        migrations.CreateModel(
            name='nabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField()),
                ('date', models.DateField()),
                ('open', models.FloatField(max_length=20)),
                ('high', models.FloatField(max_length=20)),
                ('low', models.FloatField(max_length=20)),
                ('close', models.FloatField(max_length=20)),
                ('percentage_change', models.FloatField(max_length=20)),
                ('volume', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='nepse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField()),
                ('date', models.DateField()),
                ('open', models.FloatField(max_length=20)),
                ('high', models.FloatField(max_length=20)),
                ('low', models.FloatField(max_length=20)),
                ('close', models.FloatField(max_length=20)),
                ('percentage_change', models.FloatField(max_length=20)),
                ('volume', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='a',
        ),
        migrations.DeleteModel(
            name='technical1',
        ),
        migrations.DeleteModel(
            name='tsla',
        ),
        migrations.RenameField(
            model_name='technical2',
            old_name='Holdings',
            new_name='holdings',
        ),
    ]
