# Generated by Django 4.0.2 on 2022-02-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_nabil_nepse_delete_a_delete_technical1_delete_tsla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cbbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField()),
                ('date', models.DateField()),
                ('open', models.FloatField(max_length=20)),
                ('high', models.FloatField(max_length=20)),
                ('low', models.FloatField(max_length=20)),
                ('close', models.FloatField(max_length=20)),
                ('percentage_change', models.FloatField(max_length=20)),
                ('volume', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='nica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField()),
                ('date', models.DateField()),
                ('open', models.FloatField(max_length=20)),
                ('high', models.FloatField(max_length=20)),
                ('low', models.FloatField(max_length=20)),
                ('close', models.FloatField(max_length=20)),
                ('percentage_change', models.FloatField(max_length=20)),
                ('volume', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='upper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField()),
                ('date', models.DateField()),
                ('open', models.FloatField(max_length=20)),
                ('high', models.FloatField(max_length=20)),
                ('low', models.FloatField(max_length=20)),
                ('close', models.FloatField(max_length=20)),
                ('percentage_change', models.FloatField(max_length=20)),
                ('volume', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
