# Generated by Django 4.0.2 on 2022-02-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_cbbl_nica_upper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_detail',
            name='portfolio',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='signup_detail',
            name='watchlist',
            field=models.JSONField(default=dict),
        ),
    ]
